version: "3.8"
services:
    api:
        image: lullofthesea/qwerty-shop
        build:
            dockerfile: Dockerfile
            context: .
        depends_on: 
            - postgres
        environment: 
            - DATABASE_URL=postgres://qwerty_shop_user:qwerty_shop_password@postgres:5432/qwerty_shop
            - JWT_EXPIRES_IN=600s
            - JWT_SECRET_KEY=e2146e9a-7ce6-4a0c-951e-b1c4a4422661
            - NODE_ENV=production
            - PORT=8080
        ports:
            - "8080:8080"

    postgres:
        image: postgres:latest
        ports:
            - "5432:5432"
        environment: 
            - POSTGRES_USER=qwerty_shop_user
            - POSTGRES_PASSWORD=qwerty_shop_password
            - POSTGRES_DB=qwerty_shop